nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Accept']
        expose_headers: ['Link', 'Content-Type']
        allow_credentials: false
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Accept']
            expose_headers: ['Link', 'Content-Type']
            max_age: 3600
            origin_regex: false
